name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
      
    - name: Nuclear cleanup
      run: |
        # АБСОЛЮТНАЯ очистка всех следов CMake
        find . -name "CMakeCache.txt" -delete
        find . -name "*.cmake" -delete
        find . -type d -name "CMakeFiles" -exec rm -rf {} + 2>/dev/null || true
        find . -type d -name "build" -exec rm -rf {} + 2>/dev/null || true
        rm -rf build/ CMakeFiles/ 2>/dev/null || true
        echo "Cleanup completed"
      
    - name: Build project
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        echo "Build completed"
      
    - name: Run tests
      run: |
        cd build
        ctest --verbose --output-on-failure