name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
      
    - name: Build and test
      run: |
        # Удаляем старый кэш CMake, если он существует
        rm -f CMakeCache.txt
        rm -rf build/
        
        # Создаем чистую сборку
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        
        # Запускаем тесты
        cd build
        ctest --output-on-failure