name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
      
    - name: Build and test in clean environment
      run: |
        # Временная чистая директория
        TEMP_DIR="/tmp/$(date +%s)"
        git clone . "$TEMP_DIR"
        cd "$TEMP_DIR"
        
        # Сборка и тесты
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cd build
        ctest --output-on-failure