name: C++ CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev
      
    - name: Force clean build directory
      run: |
        # Полная очистка ВСЕХ следов CMake
        rm -rf build/ CMakeCache.txt CMakeFiles/ 2>/dev/null || true
        find . -name "CMakeCache.txt" -delete 2>/dev/null || true
        find . -type d -name "CMakeFiles" -exec rm -rf {} + 2>/dev/null || true
      
    - name: Build project
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
      
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure